version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ELASTIC_PASSWORD=SomePass@"
    ports:
      - "9200:9200"
    volumes:
      - ./movies.json:/usr/share/elasticsearch/data/movies.json
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  kibana:
    image: kibana:8.13.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 500M

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6378:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass SomePass@

  endpoints:
    container_name: endpoints
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - redis
      - elasticsearch
    environment:
      - REDIS_HOST=redis
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ELASTICSEARCH_PORT=9200
    ports:
      - "8000:8000"
